version: '3.8'

services:
    api:
        build: ./
        command: uvicorn app:app --host 0.0.0.0 --port 8000
        ports:
            - 8000:8000
        depends_on:
            - db

    db:
        image: postgres:14-alpine
        environment:
            - POSTGRES_USER=$db_user
            - POSTGRES_PASSWORD=$db_pass
            - POSTGRES_DB=$db_name
        ports:
            - 5431:5432
            